import 'package:flutter/material.dart';

/// Centralized localization service for Hissab.
/// Supports English ('en'), Arabic ('ar'), and Urdu ('ur') with robust RTL handling and safe fallbacks.
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ar'),
    Locale('ur'),
  ];

  static bool isRtl(String langCode) {
    return langCode == 'ar' || langCode == 'ur';
  }

  bool get isRtlLocale => isRtl(locale.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    // -------------------------------------------------------------
    // ENGLISH
    // -------------------------------------------------------------
    'en': {
      'app.title': 'Hissab',
      'app.tagline': 'Professional CashBook & Ledger',
      'home.greeting': 'Good day',
      'home.balance': 'Current Balance',
      'home.money_in': 'Money In',
      'home.money_out': 'Money Out',
      'home.net_flow': 'Net Cash Flow',
      'home.today_summary': "Today's Summary",
      'home.recent_tx': 'Recent Transactions',
      'home.view_all': 'View All',
      'home.no_tx': 'No transactions recorded yet.',
      'home.quick_in': 'Money In (+)',
      'home.quick_out': 'Money Out (-)',

      'nav.home': 'Home',
      'nav.transactions': 'Transactions',
      'nav.parties': 'Parties',
      'nav.reports': 'Reports',
      'nav.settings': 'Settings',
      'nav.more': 'More',

      'books.title': 'My Books',
      'books.create': 'Create New Book',
      'books.name': 'Book Name',
      'books.currency': 'Currency',
      'books.opening_balance': 'Opening Balance',
      'books.opening_date': 'Opening Balance Date',
      'books.switch': 'Switch Book',
      'books.archive': 'Archive Book',
      'books.delete': 'Delete Book',
      'books.empty': 'No books available. Create one to get started.',
      'books.color_theme': 'Book Color Theme',
      'books.select_book': 'Select Book',

      'tx.add_in': 'Record Money In',
      'tx.add_out': 'Record Money Out',
      'tx.edit': 'Edit Transaction',
      'tx.details': 'Transaction Details',
      'tx.amount': 'Amount',
      'tx.category': 'Category',
      'tx.party': 'Party / Contact',
      'tx.account': 'Account',
      'tx.date': 'Date',
      'tx.time': 'Time',
      'tx.payment_method': 'Payment Method',
      'tx.description': 'Description / Note',
      'tx.reference': 'Reference / Receipt #',
      'tx.attachment': 'Attach Receipt',
      'tx.save': 'Save Transaction',
      'tx.delete_confirm': 'Delete this transaction?',
      'tx.delete_sub': 'This transaction will be moved to deleted items.',
      'tx.deleted_success': 'Transaction deleted.',
      'tx.saved_success': 'Transaction recorded successfully.',
      'tx.invalid_amount': 'Please enter a valid amount greater than 0.',

      'voice.listening': 'Listening...',
      'voice.tap_to_speak': 'Tap to speak',
      'voice.speak_now': 'Speak transaction details (e.g. Paid 500 SAR for Office Rent)',
      'voice.pause': 'Pause',
      'voice.resume': 'Resume',
      'voice.done': 'Done',
      'voice.permission_required': 'Microphone permission is required for voice input.',
      'voice.not_available': 'Speech recognition not available on this device.',

      'parties.title': 'Parties & Ledger',
      'parties.add': 'Add New Party',
      'parties.customer': 'Customer',
      'parties.supplier': 'Supplier',
      'parties.employee': 'Employee',
      'parties.other': 'Other',
      'parties.receivable': 'Owed to You (Receivable)',
      'parties.payable': 'You Owe (Payable)',
      'parties.net_balance': 'Outstanding Balance',
      'parties.total_sales': 'Total Sales / Billed',
      'parties.total_received': 'Total Received',
      'parties.total_purchases': 'Total Purchases',
      'parties.total_paid': 'Total Paid',
      'parties.no_parties': 'No parties registered yet.',
      'parties.statement': 'Party Statement',

      'reports.title': 'Financial Reports',
      'reports.income_breakdown': 'Income Breakdown',
      'reports.expense_breakdown': 'Expense Breakdown',
      'reports.daily_flow': 'Daily Cash Flow',
      'reports.monthly_comparison': 'Monthly Comparison',
      'reports.export_pdf': 'Export PDF Report',
      'reports.export_csv': 'Export CSV / Excel',
      'reports.range_today': 'Today',
      'reports.range_yesterday': 'Yesterday',
      'reports.range_this_week': 'This Week',
      'reports.range_this_month': 'This Month',
      'reports.range_this_year': 'This Year',
      'reports.range_custom': 'Custom Range',

      'accounts.title': 'Accounts & Wallets',
      'accounts.transfer': 'Internal Transfer',
      'accounts.from': 'From Account',
      'accounts.to': 'To Account',
      'accounts.cash': 'Cash in Hand',
      'accounts.bank': 'Bank Account',
      'accounts.mada': 'Mada / Card',
      'accounts.wallet': 'Digital Wallet',

      'settings.title': 'Settings',
      'settings.language': 'Language',
      'settings.theme': 'Dark Mode',
      'settings.security': 'Security & App Lock',
      'settings.pin': 'PIN Protection',
      'settings.backup': 'Cloud & Local Backup',
      'settings.restore': 'Restore Backup',
      'settings.export': 'Data Export',
      'settings.audit_log': 'Audit Trail',
      'settings.reconcile': 'Ledger Audit / Reconciliation',
      'settings.about': 'About Hissab',

      'bank.choose_logo': 'Choose Logo',
      'bank.saudi_arabia': 'Saudi Arabia',
      'bank.pakistan': 'Pakistan',
      'bank.custom_logo': 'Custom Logo',
      'bank.search_bank': 'Search bank...',
      'bank.import_logo': 'Import Custom Logo',
      'bank.remove_logo': 'Remove Logo',
      'bank.preview': 'Book Preview',
      'bank.hissab_avatar': 'Hissab Initial Avatar',
      'bank.bank_logo': 'Bank Logo',
      'bank.custom_imported': 'Custom Imported Logo',
      'bank.choose_bank': 'Select Bank',

      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.search': 'Search...',
      'common.all': 'All',
      'common.done': 'Done',
      'common.close': 'Close',
      'common.confirm': 'Confirm',
      'common.yes': 'Yes',
      'common.no': 'No',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.required': 'Required',
    },

    // -------------------------------------------------------------
    // ARABIC (العربية)
    // -------------------------------------------------------------
    'ar': {
      'app.title': 'حِساب',
      'app.tagline': 'دفتر الأستاذ والنقدية الاحترافي',
      'home.greeting': 'مرحباً بك',
      'home.balance': 'الرصيد الحالي',
      'home.money_in': 'وارد (دخل)',
      'home.money_out': 'صادر (مصروف)',
      'home.net_flow': 'صافي التدفق النقدي',
      'home.today_summary': 'ملخص اليوم',
      'home.recent_tx': 'أحدث المعاملات',
      'home.view_all': 'عرض الكل',
      'home.no_tx': 'لا توجد معاملات مسجلة بعد.',
      'home.quick_in': 'وارد (+)',
      'home.quick_out': 'صادر (-)',

      'nav.home': 'الرئيسية',
      'nav.transactions': 'المعاملات',
      'nav.parties': 'الأطراف',
      'nav.reports': 'التقارير',
      'nav.settings': 'الإعدادات',
      'nav.more': 'المزيد',

      'books.title': 'دفاتري',
      'books.create': 'إنشاء دفتر جديد',
      'books.name': 'اسم الدفتر',
      'books.currency': 'العملة',
      'books.opening_balance': 'الرصيد الافتتاحي',
      'books.opening_date': 'تاريخ الرصيد الافتتاحي',
      'books.switch': 'تبديل الدفتر',
      'books.archive': 'أرشفة الدفتر',
      'books.delete': 'حذف الدفتر',
      'books.empty': 'لا توجد دفاتر. أنشئ دفتراً للبدء.',
      'books.color_theme': 'لون الدفتر',
      'books.select_book': 'اختر الدفتر',

      'tx.add_in': 'تسجيل وارد (قبض)',
      'tx.add_out': 'تسجيل صادر (صرف)',
      'tx.edit': 'تعديل المعاملة',
      'tx.details': 'تفاصيل المعاملة',
      'tx.amount': 'المبلغ',
      'tx.category': 'التصنيف',
      'tx.party': 'الطرف / الشخص',
      'tx.account': 'الحساب',
      'tx.date': 'التاريخ',
      'tx.time': 'الوقت',
      'tx.payment_method': 'طريقة الدفع',
      'tx.description': 'الوصف / ملاحظة',
      'tx.reference': 'المرجع / رقم الإيصال',
      'tx.attachment': 'إرفاق إيصال',
      'tx.save': 'حفظ المعاملة',
      'tx.delete_confirm': 'هل تريد حذف هذه المعاملة؟',
      'tx.delete_sub': 'سيتم نقل هذه المعاملة للمحذوفات.',
      'tx.deleted_success': 'تم حذف المعاملة بنجاح.',
      'tx.saved_success': 'تم حفظ المعاملة بنجاح.',
      'tx.invalid_amount': 'يرجى إدخال مبلغ صحيح أكبر من 0.',

      'voice.listening': 'جارٍ الاستماع...',
      'voice.tap_to_speak': 'اضغط للتحدث',
      'voice.speak_now': 'تحدث بتفاصيل المعاملة (مثال: دفع 500 ريال إيجار المكتب)',
      'voice.pause': 'إيقاف مؤقت',
      'voice.resume': 'استئناف',
      'voice.done': 'تم',
      'voice.permission_required': 'يلزم إذن الميكروفون للإدخال الصوتي.',
      'voice.not_available': 'التعرف الصوتي غير متوفر على هذا الجهاز.',

      'parties.title': 'الأطراف وسجل الحسابات',
      'parties.add': 'إضافة طرف جديد',
      'parties.customer': 'عميل',
      'parties.supplier': 'مورد',
      'parties.employee': 'موظف',
      'parties.other': 'آخر',
      'parties.receivable': 'مستحق لك (مدين)',
      'parties.payable': 'مستحق عليك (دائن)',
      'parties.net_balance': 'الرصيد المتبقي',
      'parties.total_sales': 'إجمالي المبيعات',
      'parties.total_received': 'إجمالي المقبوض',
      'parties.total_purchases': 'إجمالي المشتريات',
      'parties.total_paid': 'إجمالي المدفوع',
      'parties.no_parties': 'لا يوجد أطراف مسجلة بعد.',
      'parties.statement': 'كشف حساب',

      'reports.title': 'التقارير المالية',
      'reports.income_breakdown': 'تحليل الوارد',
      'reports.expense_breakdown': 'تحليل الصادر',
      'reports.daily_flow': 'التدفق اليومي',
      'reports.monthly_comparison': 'المقارنة الشهرية',
      'reports.export_pdf': 'تصدير تقرير PDF',
      'reports.export_csv': 'تصدير ملف Excel/CSV',
      'reports.range_today': 'اليوم',
      'reports.range_yesterday': 'أمس',
      'reports.range_this_week': 'هذا الأسبوع',
      'reports.range_this_month': 'هذا الشهر',
      'reports.range_this_year': 'هذه السنة',
      'reports.range_custom': 'فترة مخصصة',

      'accounts.title': 'الحسابات والمحافظ',
      'accounts.transfer': 'تحويل داخلي',
      'accounts.from': 'من حساب',
      'accounts.to': 'إلى حساب',
      'accounts.cash': 'نقد في الصندوق',
      'accounts.bank': 'حساب بنكي',
      'accounts.mada': 'مدى / بطاقة',
      'accounts.wallet': 'محفظة رقمية',

      'settings.title': 'الإعدادات',
      'settings.language': 'اللغة',
      'settings.theme': 'الوضع الداكن',
      'settings.security': 'الأمان وقفل التطبيق',
      'settings.pin': 'رمز القفل (PIN)',
      'settings.backup': 'النسخ الاحتياطي',
      'settings.restore': 'استعادة البيانات',
      'settings.export': 'تصدير البيانات',
      'settings.audit_log': 'سجل العمليات (Audit Trail)',
      'settings.reconcile': 'فحص وتدقيق القيود',
      'settings.about': 'عن تطبيق حِساب',

      'bank.choose_logo': 'اختر الشعار',
      'bank.saudi_arabia': 'المملكة العربية السعودية',
      'bank.pakistan': 'باكستان',
      'bank.custom_logo': 'شعار مخصص',
      'bank.search_bank': 'البحث عن بنك...',
      'bank.import_logo': 'استيراد شعار مخصص',
      'bank.remove_logo': 'إزالة الشعار',
      'bank.preview': 'معاينة الدفتر',
      'bank.hissab_avatar': 'شعار حساب الافتراضي',
      'bank.bank_logo': 'شعار البنك',
      'bank.custom_imported': 'شعار مخصص مستورد',
      'bank.choose_bank': 'اختر البنك',

      'common.save': 'حفظ',
      'common.cancel': 'إلغاء',
      'common.delete': 'حذف',
      'common.edit': 'تعديل',
      'common.search': 'بحث...',
      'common.all': 'الكل',
      'common.done': 'تم',
      'common.close': 'إغلاق',
      'common.confirm': 'تأكيد',
      'common.yes': 'نعم',
      'common.no': 'لا',
      'common.error': 'خطأ',
      'common.success': 'نجاح',
      'common.required': 'مطلوب',
    },

    // -------------------------------------------------------------
    // URDU (اردو)
    // -------------------------------------------------------------
    'ur': {
      'app.title': 'حساب',
      'app.tagline': 'پیشہ ورانہ ڈیجیٹل کیش بک اور کھاتہ',
      'home.greeting': 'خوش آمدید',
      'home.balance': 'موجودہ بیلنس',
      'home.money_in': 'آمدنی (ان)',
      'home.money_out': 'اخراجات (آؤٹ)',
      'home.net_flow': 'خالص کیش فلو',
      'home.today_summary': 'آج کا خلاصہ',
      'home.recent_tx': 'حالیہ ٹرانزیکشنز',
      'home.view_all': 'سب دیکھیں',
      'home.no_tx': 'ابھی تک کوئی اندراج موجود نہیں۔',
      'home.quick_in': 'پیسے آئے (+)',
      'home.quick_out': 'پیسے گئے (-)',

      'nav.home': 'ہوم',
      'nav.transactions': 'لین دین',
      'nav.parties': 'کھاتے / پارٹیاں',
      'nav.reports': 'رپورٹس',
      'nav.settings': 'سیٹنگز',
      'nav.more': 'مزید',

      'books.title': 'میری کتب / کیش بکس',
      'books.create': 'نئی بک بنائیں',
      'books.name': 'بک کا نام',
      'books.currency': 'کرنسی',
      'books.opening_balance': 'ابتدائی بیلنس',
      'books.opening_date': 'ابتدائی بیلنس کی تاریخ',
      'books.switch': 'بک تبدیل کریں',
      'books.archive': 'محفوظ کریں (آرکائیو)',
      'books.delete': 'بک ڈیلیٹ کریں',
      'books.empty': 'کوئی بک موجود نہیں ہے۔ شروع کرنے کے لیے نئی بک بنائیں۔',
      'books.color_theme': 'بک کا رنگ و تھیم',
      'books.select_book': 'بک منتخب کریں',

      'tx.add_in': 'آمدنی کا اندراج',
      'tx.add_out': 'خرچ کا اندراج',
      'tx.edit': 'اندراج میں ترمیم',
      'tx.details': 'ٹرانزیکشن کی تفصیلات',
      'tx.amount': 'رقم',
      'tx.category': 'کیٹیگری',
      'tx.party': 'پارٹی / کسٹمر',
      'tx.account': 'اکاؤنٹ',
      'tx.date': 'تاریخ',
      'tx.time': 'وقت',
      'tx.payment_method': 'ادائیگی کا طریقہ',
      'tx.description': 'تفصیل / نوٹ',
      'tx.reference': 'رسید نمبر / حوالہ',
      'tx.attachment': 'رسید منسلک کریں',
      'tx.save': 'اندراج محفوظ کریں',
      'tx.delete_confirm': 'کیا آپ یہ اندراج ڈیلیٹ کرنا چاہتے ہیں؟',
      'tx.delete_sub': 'یہ اندراج ردی کی ٹوکری میں منتقل ہو جائے گا۔',
      'tx.deleted_success': 'اندراج کامیابی سے ڈیلیٹ کر دیا گیا۔',
      'tx.saved_success': 'اندراج کامیابی سے محفوظ ہو گیا۔',
      'tx.invalid_amount': 'براہ کرم 0 سے بڑی درست رقم درج کریں۔',

      'voice.listening': 'سن رہا ہے...',
      'voice.tap_to_speak': 'بولنے کے لیے ٹیپ کریں',
      'voice.speak_now': 'ٹرانزیکشن بولیں (مثلاً: آفس کرایہ 500 ریال دیا)',
      'voice.pause': 'روکیں',
      'voice.resume': 'دوبارہ شروع کریں',
      'voice.done': 'مکمل',
      'voice.permission_required': 'آواز سے اندراج کے لیے مائیکروفون کی اجازت درکار ہے۔',
      'voice.not_available': 'اس ڈیوائس پر آواز کی شناخت دستیاب نہیں ہے۔',

      'parties.title': 'پارٹیاں اور کھاتہ',
      'parties.add': 'نئی پارٹی شامل کریں',
      'parties.customer': 'کسٹمر (گاہک)',
      'parties.supplier': 'سپلائر (دکاندار)',
      'parties.employee': 'ملازم',
      'parties.other': 'دیگر',
      'parties.receivable': 'لینے ہیں (Receivable)',
      'parties.payable': 'دینے ہیں (Payable)',
      'parties.net_balance': 'باقی رقم',
      'parties.total_sales': 'کل فروخت',
      'parties.total_received': 'کل موصول رقم',
      'parties.total_purchases': 'کل خریداری',
      'parties.total_paid': 'کل ادا شدہ رقم',
      'parties.no_parties': 'کوئی پارٹی موجود نہیں ہے۔',
      'parties.statement': 'کھاتہ کی تفصیل',

      'reports.title': 'مالیاتی رپورٹس',
      'reports.income_breakdown': 'آمدنی کا تجزیہ',
      'reports.expense_breakdown': 'اخراجات کا تجزیہ',
      'reports.daily_flow': 'روزانہ کیش فلو',
      'reports.monthly_comparison': 'ماہانہ موازنہ',
      'reports.export_pdf': 'پی ڈی ایف رپورٹ بنائیں',
      'reports.export_csv': 'ایکسل / CSV برآمد کریں',
      'reports.range_today': 'آج',
      'reports.range_yesterday': 'کل',
      'reports.range_this_week': 'اس ہفتے',
      'reports.range_this_month': 'اس ماہ',
      'reports.range_this_year': 'اس سال',
      'reports.range_custom': 'مخصوص مدت',

      'accounts.title': 'اکاؤنٹس اور بٹوے',
      'accounts.transfer': 'داخلی ٹرانسفر',
      'accounts.from': 'کس اکاؤنٹ سے',
      'accounts.to': 'کس اکاؤنٹ میں',
      'accounts.cash': 'کیش ان ہینڈ',
      'accounts.bank': 'بینک اکاؤنٹ',
      'accounts.mada': 'کارڈ / مادا',
      'accounts.wallet': 'ڈیجیٹل والٹ',

      'settings.title': 'سیٹنگز',
      'settings.language': 'زبان',
      'settings.theme': 'ڈارک موڈ',
      'settings.security': 'سیکیورٹی اور لاک',
      'settings.pin': 'پن کوڈ (PIN)',
      'settings.backup': 'بیک اپ بنائیں',
      'settings.restore': 'ڈیٹا بحال کریں',
      'settings.export': 'ڈیٹا برآمد کریں',
      'settings.audit_log': 'آڈٹ لاگ',
      'settings.reconcile': 'لیجر اور بیلنس کی جانچ',
      'settings.about': 'حساب کے بارے میں',

      'bank.choose_logo': 'لوگو منتخب کریں',
      'bank.saudi_arabia': 'سعودی عرب',
      'bank.pakistan': 'پاکستان',
      'bank.custom_logo': 'اپنا لوگو',
      'bank.search_bank': 'بینک تلاش کریں...',
      'bank.import_logo': 'لوگو درآمد کریں',
      'bank.remove_logo': 'لوگو حذف کریں',
      'bank.preview': 'بک کا پیش منظر',
      'bank.hissab_avatar': 'حساب کا ابتدائی اوتار',
      'bank.bank_logo': 'بینک کا لوگو',
      'bank.custom_imported': 'درآمد شدہ ذاتی لوگو',
      'bank.choose_bank': 'بینک منتخب کریں',

      'common.save': 'محفوظ کریں',
      'common.cancel': 'منسوخ کریں',
      'common.delete': 'ڈیلیٹ کریں',
      'common.edit': 'ترمیم کریں',
      'common.search': 'تلاش کریں...',
      'common.all': 'سب',
      'common.done': 'مکمل',
      'common.close': 'بند کریں',
      'common.confirm': 'تصدیق کریں',
      'common.yes': 'ہاں',
      'common.no': 'نہیں',
      'common.error': 'خرابی',
      'common.success': 'کامیابی',
      'common.required': 'لازمی',
    },
  };

  /// Translate key with fallback to English, then optional fallback or key itself.
  /// Guaranteed NEVER to throw an unhandled exception.
  String translate(String key, {String? fallback}) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        fallback ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar', 'ur'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
